# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]

[[plugins]]
  # Installs the Gatsby Build Plugin for all deploy contexts
  package = "@netlify/plugin-gatsby"